### ISSUE TITLE
afni_refacer Error: can't find input file

### ISSUE THREAD

**Issue by qinychen** [PennLINC/afni_refacer#1]
Dear afni_refacer experts,

I try to use afni_refacer in docker container in my local computer. The OS of my computer is Ubuntu 18. But when I type the command under the directory that I stored my data: 
docker run pennlinc/afni_refacer  \
        -input anat_T1w.nii.gz    \
        -mode_reface \
        -prefix anat_T1w_reface.nii.gz
Error: can't find input file was reported
I also try to added the pathway in front of the filename, but the error was reported again.
Does anyone know how to fix this? Many thanks in advance!

Best regards,
Qinyuan

**Comment by JiaBob** [comment]
Hi my friend. Not sure if the author had already helped you. The problem is due to the basis of docker. You have to mount your local directory to the place of the docker, by:
docker run -v [absolute path of your directory contains your nii data]:[absolute path of docker] -input [absolute path of docker]/[your file name] -mode_reface -prefix [absolute path of docker]/[output_name]

Then you can find the output generated directly onto [absolute path of your directory], named [output_name].

Hope your can understand my notation. Good Luck!

**Comment by qinychen** [comment]
> Hi my friend. Not sure if the author had already helped you. The problem is due to the basis of docker. You have to mount your local directory to the place of the docker, by: docker run -v [absolute path of your directory contains your nii data]:[absolute path of docker] -input [absolute path of docker]/[your file name] -mode_reface -prefix [absolute path of docker]/[output_name]
> 
> Then you can find the output generated directly onto [absolute path of your directory], named [output_name].
> 
> Hope your can understand my notation. Good Luck!

Hi JiaBob,

Thank you for your reply! It works!

Best regards,
Qinyuan
